spring:
  application:
    name: user-service
  config:
    import: "configserver:http://localhost:8081"
  cloud:
    config:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/base-realm
